version: "3"

services:

  nginx:
    image: nginx:mainline
    restart: always
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./statics:/usr/share/nginx/html/statics:ro
      - ./nginx.d:/etc/nginx/conf.d:ro
      - ./secrets:/secrets:ro

  wordpress:
    image: wordpress:php7.0-apache
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_

  api:
    image: python:3
    restart: always

  db:
    image: mysql
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress

# networks:
#   default:
#     internal: true
#   expose:
#     driver: bridge
